// Client side: actually connect to our headless server.
//
// NOTE FOR `foundation`: new file only -- I have not touched auth_token.cpp or
// network.cpp. The coordinator handed me the end-to-end join, and this is the client
// half of it. Move or fold it into yours as you like.
//
// WHY THIS EXISTS: `+connect` is not a client command in this exe at all. `connect`
// exists only as the server-side out-of-band name at 0x635253, which is why a client
// launched with `+connect 127.0.0.1:28960` sat at the menu doing nothing (run join1).
// T4's equivalent of iw4x's `connect_coop` is the function at 0x641730.
//
// CONVENTION, PROVEN FROM THE INSTRUCTIONS (not inferred -- that mistake has cost this
// project three times tonight). Disassembled from re's flat dump:
//
//   00641730  push ebp / mov ebp,esp / and esp,0xFFFFFFF8   args at [ebp+8], [ebp+0Ch]
//   00641883  call 0x642C80                                 CL_SendConnectPacket
//   006418BF  cmp byte ptr [ebp+0Ch], bl                    arg2 is a byte/bool
//   006418D9  mov esi, dword ptr [ebp+8]                    arg1 is a dword...
//   006418DC  mov eax, 0x87B6D0 / mov edx,esi / call 5F6AF0  ...compared as a string
//   0064194F  ret                                           plain ret, NOT ret 8
//
// and both call sites clean up themselves:
//   0x6321A2  call 0x641730 ; add esp, 8     (the map-load path)
//   0x65838A  call 0x641730 ; add esp, 8
//
//   => void __cdecl CL_ConnectLocal(const char* mapName, int flag);
//
// 0x87B6D0 is the literal "credits", which arg1 is compared against, so arg1 is a map
// name. 0x86F0D4 is "localhost": this function hardcodes the local server, which is
// exactly what we want for the loopback test.
//
// THE GATE IS NOT A GATE. The brief said client state at [0x305842C] must be >= 6 or
// the connect branch never runs. It is the opposite: `jl 0x6417D2` jumps INTO the
// connect path when state < 6, and the >= 6 fall-through only early-outs if we are
// already on "localhost". A freshly launched, disconnected client (state 0) therefore
// takes the connect path with nothing to set up first.
//
// HOW IT FIRES: no console command, because registering one would mean trusting an
// unverified Cmd_AddCommand. Set ENW_CLIENT_CONNECT=<mapname> and we call it once from
// the shared frame tick, on the main thread, when the gate below opens.
//
// WHEN IT FIRES (2026-09-22, replaces "blindly at frame 300"). Frame 300 is ~1.2 s at
// com_maxfps 250, and B's run enw-11524 connected 2.0 s after post_init while a Bink
// video was still up: the video drew over the HUD and one run died in
// Hunk_AllocateTempMemory. So we now wait until the client is SAFE, on the main thread:
//   1. no FILE Bink video open (the Treyarch intro, a <map>_load.bik). The menu's own
//      background is a fastfile Bink that is open the whole time the menu is up
//      (gate1: opened 0.9 s after post_init, closed only by the connect), so it cannot
//      count -- its first open is used as "the menu is up" instead. We wrap the IAT slots for _BinkOpen@8 (0x7EB42C)
//      and _BinkClose@4 (0x7EB418). The only BinkOpen caller is 0x6EB3B0, which handles
//      a NULL return (prints "BinkOpen: %s"). IAT, not the .def: binkw32.def is
//      generated by tools/dev/gen-proxy-def.py and says DO NOT EDIT.
//   2. clc.state [0x305842C] != 1. 1 is CA_CINEMATIC: the `cinematic` command's player
//      (0x46F170) writes `mov [edx*4+0x305842C], 1` at 0x46F296.
//   3. all true for kSettleMs straight, and no sooner than kFloorMs after post_init.
// Ceiling: at kCeilingMs we fire anyway and say so at WARN -- a gate that never opens
// costs a late join, not no join.
//
// WHAT B SAW IS THE MAP'S LOAD VIDEO, NOT THE STARTUP INTRO (gate1, 2026-09-22): with
// our args no Treyarch open happens at all; nazi_zombie_prototype_load.bik opens 35 ms
// after CL_ConnectLocal and stays open 28 s -- the level was live after 3.3 s. So for a
// launcher join BinkOpen refuses "*_load.bik" (ENW_ALLOW_LOAD_VIDEO=1 turns that off).
//
// THE STARTUP INTRO. Com_Init (0x59CEB0) queues "cinematic Treyarch\n" (0x872584) at
// 0x59D684 only if com_startupIntroPlayed (dvar ptr 0x1F96494) is 0; the cinematic
// player skips "Treyarch" when com_introPlayed (dvar ptr 0x1F964A4) is 1 and fs_game is
// set. Both are on our command line and both are 1 in the profile config, so statically
// it should not play. Belt: BinkOpen refuses a FILE open whose path contains "Treyarch"
// (ENW_ALLOW_INTRO=1 turns that off), and every open is logged, so the next run names
// the video B actually saw.
//
// Clean room: our own code.

#include "boot_direct.hpp"
#include "component.hpp"
#include "frame.hpp"
#include "logger.hpp"
#include "memory.hpp"

#include <windows.h>

#include <cstdlib>
#include <cstring>

namespace enw::client {
namespace {

constexpr uintptr_t kCL_ConnectLocal = 0x641730;
constexpr uintptr_t kClcState = 0x305842C;
constexpr int kCaCinematic = 1;

// The first six bytes of the function, from the dump. If the image does not match we
// refuse to call rather than jump into the middle of something.
constexpr uint8_t kPrologue[] = {0x55, 0x8B, 0xEC, 0x83, 0xE4, 0xF8};

constexpr ULONGLONG kFloorMs = 2000;
constexpr ULONGLONG kSettleMs = 750;
constexpr ULONGLONG kCeilingMs = 30000;

// Bink open flags as the engine passes them: 0x04104400 from a fastfile rawfile
// (0x6EB42E, the "name" is a memory pointer), 0x01104400 from disk (0x6EB47E, a path).
constexpr unsigned kBinkFromMemory = 0x04000000;
constexpr unsigned kBinkFileHandle = 0x00800000;

using CL_ConnectLocal_t = void(__cdecl*)(const char*, int);
using BinkOpen_t = void*(__stdcall*)(const char*, unsigned);
using BinkClose_t = void(__stdcall*)(void*);

char g_map[64] = {};
bool g_armed = false;
bool g_fired = false;
bool g_block_intro = true;
bool g_count_valid = false;  // both halves hooked

BinkOpen_t g_bink_open = nullptr;
BinkClose_t g_bink_close = nullptr;
volatile LONG g_bink_live = 0;   // FILE videos open right now (intro, <map>_load)
volatile LONG g_bink_total = 0;  // opens this session, any kind
volatile LONG g_bink_memory = 0; // fastfile opens this session: the menu background
void* volatile g_bink_handles[16] = {};  // FILE handles only
bool g_block_load = true;
volatile ULONGLONG g_connect_tick = 0;  // GetTickCount64 at our CL_ConnectLocal

bool contains_nocase(const char* hay, const char* needle) {
    const size_t n = std::strlen(needle);
    for (; *hay; ++hay)
        if (_strnicmp(hay, needle, n) == 0) return true;
    return false;
}

void* __stdcall bink_open_detour(const char* name, unsigned flags) {
    const bool is_path = name && !(flags & (kBinkFromMemory | kBinkFileHandle));
    if (is_path && g_block_intro && contains_nocase(name, "Treyarch")) {
        ENW_INFO("bink: REFUSED the startup intro '%s' (flags 0x%08X); the engine handles a "
                 "NULL BinkOpen. ENW_ALLOW_INTRO=1 lets it play.", name, flags);
        return nullptr;
    }
    // A launcher join: the map's load video outlives the load by ~25 s and draws over
    // the game (gate1, 2026-09-22). Refuse it; the loadscreen image still shows.
    // Refusing it makes the engine fall back to main/video/default.bik (gate2: it then
    // played 10 s, 7 s into the game), so default.bik is refused too for 60 s from our
    // connect -- the load's fallback, not a map's own later use of it.
    const bool fallback = is_path && g_connect_tick &&
                          ::GetTickCount64() - g_connect_tick < 60000 &&
                          contains_nocase(name, "default.bik");
    if (is_path && g_armed && g_block_load && (contains_nocase(name, "_load.bik") || fallback)) {
        ENW_INFO("bink: REFUSED the load video '%s' for this join; the engine handles a "
                 "NULL BinkOpen. ENW_ALLOW_LOAD_VIDEO=1 lets it play.", name);
        return nullptr;
    }
    void* h = g_bink_open ? g_bink_open(name, flags) : nullptr;
    const LONG total = ::InterlockedIncrement(&g_bink_total);
    if (h && !is_path) ::InterlockedIncrement(&g_bink_memory);
    if (h && is_path) {
        for (auto& slot : g_bink_handles)
            if (::InterlockedCompareExchangePointer(&slot, h, nullptr) == nullptr) {
                ::InterlockedIncrement(&g_bink_live);
                break;
            }
    }
    ENW_INFO("bink: open #%ld %s '%s' flags 0x%08X -> %p (%ld open)", static_cast<long>(total),
             is_path ? "file" : "memory", is_path ? name : "-", flags, h,
             static_cast<long>(g_bink_live));
    return h;
}

void __stdcall bink_close_detour(void* h) {
    if (h)
        for (auto& slot : g_bink_handles)
            if (::InterlockedCompareExchangePointer(&slot, nullptr, h) == h) {
                ::InterlockedDecrement(&g_bink_live);
                break;
            }
    ENW_INFO("bink: close %p (%ld open)", h, static_cast<long>(g_bink_live));
    if (g_bink_close) g_bink_close(h);
}

int clc_state() { return *reinterpret_cast<const volatile int*>(enw::at(kClcState)); }

void try_connect() {
    if (g_fired) return;
    g_fired = true;

    const uintptr_t live = enw::at(kCL_ConnectLocal);
    uint8_t got[sizeof kPrologue] = {};
    if (!memory::read_raw(live, got, sizeof got) ||
        std::memcmp(got, kPrologue, sizeof got) != 0) {
        ENW_ERROR("connect_local: 0x%08X does not have the expected prologue (%s); refusing to call",
                  static_cast<unsigned>(kCL_ConnectLocal),
                  memory::hex_dump(live, 8).c_str());
        return;
    }

    ENW_INFO("connect_local: calling CL_ConnectLocal(\"%s\", 0) at 0x%08X", g_map,
             static_cast<unsigned>(kCL_ConnectLocal));
    g_connect_tick = ::GetTickCount64();
    const auto fn = reinterpret_cast<CL_ConnectLocal_t>(live);
    fn(g_map, 0);
    boot_direct::note_connect();
    ENW_INFO("connect_local: returned; client state [0x305842C] = %d", clc_state());
}

ULONGLONG g_t0 = 0;          // post_init
ULONGLONG g_safe_since = 0;  // 0 = not safe right now

void gate_tick(uint64_t frame) {
    if (g_fired) return;
    const ULONGLONG now = ::GetTickCount64();
    const ULONGLONG age = now - g_t0;
    const int state = clc_state();
    const LONG videos = g_count_valid ? g_bink_live : 0;
    // The menu's background loop is a fastfile (memory) Bink that stays open for as
    // long as the menu is up, so "no video open" can only mean no FILE video. Its
    // first open is also our "the main menu is up" signal; 6 s stands in if a mod's
    // menu has none.
    const bool menu_up = g_bink_memory > 0 || age >= 6000;
    const bool safe = videos == 0 && state != kCaCinematic && menu_up;
    // boot_direct.cpp: an armed launcher join does not wait for the menu at all.
    if (boot_direct::fire_now(frame, age, state, videos)) {
        try_connect();
        return;
    }
    if (!safe) g_safe_since = 0;
    else if (!g_safe_since) g_safe_since = now;

    if (age >= kFloorMs && g_safe_since && now - g_safe_since >= kSettleMs) {
        ENW_INFO("connect_local: gate OPEN %llu ms after post_init (frame %llu): no video open "
                 "(%ld opened this session, %ld menu%s), clc.state=%d, safe for %llu ms",
                 age, static_cast<unsigned long long>(frame), static_cast<long>(g_bink_total),
                 static_cast<long>(g_bink_memory),
                 g_count_valid ? "" : ", COUNT NOT HOOKED", state, now - g_safe_since);
        try_connect();
    } else if (age >= kCeilingMs) {
        ENW_WARN("connect_local: gate NEVER OPENED in %llu ms (videos open=%ld, clc.state=%d) "
                 "- connecting anyway. If a video shows over the game, this is why.",
                 age, static_cast<long>(videos), state);
        try_connect();
    }
}

class connect_local_component final : public component {
public:
    const char* name() const override { return "connect_local"; }

    void post_load() override {
        // The Bink watch is always on, joining or not: the logged video names are the
        // evidence for what plays at startup.
        const char* ai = std::getenv("ENW_ALLOW_INTRO");
        g_block_intro = !(ai && *ai == '1');
        const char* al = std::getenv("ENW_ALLOW_LOAD_VIDEO");
        g_block_load = !(al && *al == '1');
        const bool o = memory::hook_import("binkw32.dll", "_BinkOpen@8",
                                           reinterpret_cast<void*>(&bink_open_detour),
                                           reinterpret_cast<void**>(&g_bink_open));
        const bool c = memory::hook_import("binkw32.dll", "_BinkClose@4",
                                           reinterpret_cast<void*>(&bink_close_detour),
                                           reinterpret_cast<void**>(&g_bink_close));
        g_count_valid = o && c;  // a half hook counts opens and never closes
        if (g_count_valid)
            ENW_INFO("bink: watching BinkOpen/BinkClose through the game's IAT (intro %s)",
                     g_block_intro ? "blocked" : "allowed");
        else
            ENW_WARN("bink: IAT hook incomplete (open=%d close=%d); the join gate uses "
                     "clc.state and the clock only", o, c);

        const char* m = std::getenv("ENW_CLIENT_CONNECT");
        if (!m || !*m) return;
        // NEVER on the server. A full build compiles client-dll components into the
        // dedicated DLL too, and the join test exports ENW_CLIENT_CONNECT to both
        // processes -- without this the server would try to connect to itself.
        // Checked from the command line because the dedicated component is not linked
        // into a client-only build.
        const char* cmd = ::GetCommandLineA();
        if (cmd && std::strstr(cmd, "dedicated 1")) {
            ENW_INFO("connect_local: this process is a dedicated server; not arming");
            return;
        }
        std::strncpy(g_map, m, sizeof g_map - 1);
        g_armed = true;
        ENW_INFO("connect_local: armed for map '%s' (map load video %s)", g_map,
                 g_block_load ? "blocked" : "allowed");
    }

    void post_init() override {
        if (!g_armed) return;
        g_t0 = ::GetTickCount64();
        enw::frame::subscribe("connect_local", gate_tick);
        ENW_INFO("connect_local: will fire once the menu is up, no file video is open and "
                 "clc.state != 1 for "
                 "%llu ms, no sooner than %llu ms after now, and at %llu ms regardless "
                 "(frame tick installed=%s)", kSettleMs, kFloorMs, kCeilingMs,
                 enw::frame::installed() ? "yes" : "NO");
    }
};

}  // namespace
}  // namespace enw::client

ENW_REGISTER_COMPONENT(enw::client::connect_local_component)
