// The in-game Settings tab's model: the schema, what may be shown, and the console text
// a change becomes. Pure: no engine, no window, no file -- so it is unit-tested
// (tools/tests/settings_model_test.cpp, built as settings_model_test by CMakeLists.txt).
//
// THE LIST IS NOT HERE. It is shared/settings/ingame-settings.json, generated by
// tools/settings/gen-ingame-schema.mjs from the site's own catalogue
// (web/client/src/data/wawSettings.js + settingsLayout.js) and embedded into the DLL at
// build time. This file only knows how to read it. esc-menu.md §9 is the write-up.
#pragma once

#include "json.hpp"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <map>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace enw::settings {

enum class kind { toggle, select, slider, bind, info };
enum class apply { live, vid_restart, next_launch, site };

struct item {
    std::string id, label, dvar, command, def, enw_def, hint, to;
    kind k = kind::info;
    apply a = apply::live;
    bool verified = false;
    bool not_borderless = false;
    bool free_values = false;
    std::vector<std::string> values, labels, def_keys;
    double min = 0, max = 0, step = 0;
    // value -> the other dvars the game's own menu script sets with it (Invert Mouse ->
    // m_pitch, Mature -> cg_blood).
    std::map<std::string, std::vector<std::pair<std::string, std::string>>> also;
};

struct group { std::string tab, id, label; std::vector<size_t> items; };
struct tab { std::string id, label; };

struct schema {
    std::vector<tab> tabs;
    std::vector<group> groups;
    std::vector<item> items;
    size_t excluded = 0;
    const item* find(std::string_view id) const {
        for (const auto& i : items) if (i.id == id) return &i;
        return nullptr;
    }
};

inline std::string lower(std::string_view s) {
    std::string o(s);
    for (auto& c : o) if (c >= 'A' && c <= 'Z') c = static_cast<char>(c - 'A' + 'a');
    return o;
}

// NEVER OURS, whatever the schema says (mod-compat.md §3, README hard rule 5): the
// console / cheat switches a map's anti-cheat watches, and anything a Verified game
// forbids outright. A schema that listed one would be refused item by item at load.
inline bool forbidden_dvar(std::string_view dvar) {
    static const char* const kNever[] = {
        "monkeytoy", "con_external", "sv_cheats", "developer", "developer_script", "logfile",
        "com_introplayed", "fs_game", "fs_homepath", "fs_basepath", "sv_pure", "timescale",
        "g_speed", "g_gravity", "player_backspeedscale", "player_strafespeedscale",
        "cg_fovscale", "name", "enw_token", "enw_ui", "enw_req", "enw_pchat",
    };
    const std::string d = lower(dvar);
    for (const char* n : kNever) if (d == n) return true;
    // Gameplay prefixes are the server's (the launcher's own whitelist test allows
    // exactly ai_corpseCount, which INGAME excludes).
    for (const char* p : {"ai_", "g_", "sv_", "player_", "bg_", "perk_", "scr_"})
        if (d.rfind(p, 0) == 0) return true;
    return false;
}

inline kind kind_of(const std::string& s) {
    if (s == "toggle") return kind::toggle;
    if (s == "select") return kind::select;
    if (s == "slider") return kind::slider;
    if (s == "bind") return kind::bind;
    return kind::info;
}

// Parse the embedded schema. False (with `err`) only when nothing usable came out; an
// item that fails a check is dropped and counted in `err` as a note.
inline bool load(std::string_view text, schema* out, std::string* err) {
    json::value v;
    if (!json::parse(text, &v) || v.type != json::kind::object) { *err = "the schema is not JSON"; return false; }
    if (v.int_or("v", 0) != 1) { *err = "unknown schema version"; return false; }
    schema s;
    std::string notes;
    if (const auto* a = v.find("items"); a && a->type == json::kind::array) {
        for (const auto& x : a->items) {
            item it;
            it.id = x.str_or("id");
            it.label = x.str_or("label", it.id);
            it.k = kind_of(x.str_or("kind"));
            const std::string ap = x.str_or("apply", "live");
            it.a = ap == "vid_restart" ? apply::vid_restart : ap == "next_launch" ? apply::next_launch
                 : ap == "site" ? apply::site : apply::live;
            it.verified = x.bool_or("verified", false);
            it.not_borderless = x.bool_or("notBorderless", false);
            it.free_values = x.bool_or("free", false);
            it.dvar = x.str_or("dvar");
            it.command = x.str_or("command");
            it.to = x.str_or("to");
            it.hint = x.str_or("hint");
            it.enw_def = x.str_or("enw");
            it.min = x.num_or("min", 0);
            it.max = x.num_or("max", 0);
            it.step = x.num_or("step", 0);
            if (const auto* d = x.find("def")) {
                if (d->type == json::kind::array) { for (const auto& k : d->items) it.def_keys.push_back(k.s); }
                else if (d->type == json::kind::string) it.def = d->s;
            }
            if (const auto* vs = x.find("values"); vs && vs->type == json::kind::array)
                for (const auto& e : vs->items) it.values.push_back(e.s);
            if (const auto* ls = x.find("labels"); ls && ls->type == json::kind::array)
                for (const auto& e : ls->items) it.labels.push_back(e.s);
            if (const auto* al = x.find("also"); al && al->type == json::kind::object)
                for (const auto& [val, arr] : al->fields) {
                    if (arr.type != json::kind::array) continue;
                    for (const auto& pr : arr.items)
                        if (pr.type == json::kind::array && pr.items.size() == 2)
                            it.also[val].push_back({pr.items[0].s, pr.items[1].s});
                }
            // Checks. An id is required; a control that writes needs somewhere to write.
            bool ok = !it.id.empty();
            if (ok && it.k == kind::bind && it.command.empty()) ok = false;
            if (ok && it.k != kind::bind && it.k != kind::info && it.dvar.empty()) ok = false;
            if (ok && !it.dvar.empty() && forbidden_dvar(it.dvar)) ok = false;
            for (const auto& [val, extra] : it.also)
                for (const auto& [d, x2] : extra) if (forbidden_dvar(d)) ok = false;
            if (ok && (it.k == kind::toggle) && it.values.size() != 2) ok = false;
            if (ok && it.k == kind::select && it.values.empty()) ok = false;
            if (ok && it.k == kind::slider && !(it.max > it.min && it.step > 0)) ok = false;
            if (!ok) { notes += (notes.empty() ? "" : ", ") + (it.id.empty() ? std::string("?") : it.id); continue; }
            s.items.push_back(std::move(it));
        }
    }
    if (const auto* a = v.find("excluded"); a && a->type == json::kind::array) s.excluded = a->items.size();
    auto index_of = [&](const std::string& id) -> long {
        for (size_t i = 0; i < s.items.size(); ++i) if (s.items[i].id == id) return static_cast<long>(i);
        return -1;
    };
    if (const auto* a = v.find("groups"); a && a->type == json::kind::array)
        for (const auto& x : a->items) {
            group g{x.str_or("tab"), x.str_or("id"), x.str_or("label"), {}};
            if (const auto* ids = x.find("items"); ids && ids->type == json::kind::array)
                for (const auto& e : ids->items) { const long k = index_of(e.s); if (k >= 0) g.items.push_back(static_cast<size_t>(k)); }
            if (!g.items.empty()) s.groups.push_back(std::move(g));
        }
    if (const auto* a = v.find("tabs"); a && a->type == json::kind::array)
        for (const auto& x : a->items) {
            tab t{x.str_or("id"), x.str_or("label")};
            const bool used = std::any_of(s.groups.begin(), s.groups.end(), [&](const group& g) { return g.tab == t.id; });
            if (used) s.tabs.push_back(std::move(t));
        }
    if (s.items.empty() || s.tabs.empty()) { *err = "the schema has no usable items"; return false; }
    *err = notes.empty() ? std::string() : "dropped: " + notes;
    *out = std::move(s);
    return true;
}

// ------------------------------------------------------------------ what is shown
struct context {
    bool restricted = false;      // a Verified game (the invite token is present)
    bool borderless = false;      // the DLL's borderless window is up
    bool listen_server = false;   // Play Local: the engine refuses vid_restart
    std::vector<std::string> mod_owned;   // lower-case dvars the map sets itself
};

enum class shown { hidden, editable, readonly };

// B, 2026-09-23 (esc-menu.md §11.3): every setting is SHOWN in every game, Verified
// included. A Verified game locks (read-only) only what the records rules pin: the items
// the catalogue marks `verified: false` -- today com_maxfps alone (verified-rules.md §4).
// `hidden` is kept for callers but nothing in the catalogue is hidden any more.
inline shown visibility(const item& it, const context& c, std::string* why) {
    if (it.k == kind::info || it.a == apply::site) { if (why) *why = "set in the launcher"; return shown::readonly; }
    if (c.restricted && !it.verified) { if (why) *why = "locked in a Verified game"; return shown::readonly; }
    const std::string d = lower(it.dvar);
    if (!d.empty() && std::find(c.mod_owned.begin(), c.mod_owned.end(), d) != c.mod_owned.end()) {
        if (why) *why = "set by this map";
        return shown::readonly;
    }
    if (it.not_borderless && c.borderless) { if (why) *why = "borderless uses your monitor's size"; return shown::readonly; }
    if (why) {
        if (it.a == apply::vid_restart) *why = c.listen_server ? "applies next launch" : "needs Apply";
        else if (it.a == apply::next_launch) *why = "applies next launch";
        else why->clear();
    }
    return shown::editable;
}

// ------------------------------------------------------------------ values
inline bool is_number(const std::string& s, double* out = nullptr) {
    if (s.empty()) return false;
    char* end = nullptr;
    const double d = std::strtod(s.c_str(), &end);
    if (!end || *end != '\0') return false;
    if (out) *out = d;
    return true;
}

// Same value, the way the engine means it: "80" == "80.000000", "wide 16:9" == "Wide 16:9".
inline bool same_value(const std::string& a, const std::string& b) {
    double x, y;
    if (is_number(a, &x) && is_number(b, &y)) return std::fabs(x - y) < 1e-4;
    return lower(a) == lower(b);
}

inline int decimals_of(double step) {
    int d = 0;
    while (d < 4 && std::fabs(step * std::pow(10.0, d) - std::round(step * std::pow(10.0, d))) > 1e-6) ++d;
    return d;
}

inline std::string fmt_number(double v, int decimals) {
    char buf[64];
    std::snprintf(buf, sizeof buf, "%.*f", decimals, v);
    std::string s(buf);
    if (s.find('.') != std::string::npos) {
        while (!s.empty() && s.back() == '0') s.pop_back();
        if (!s.empty() && s.back() == '.') s.pop_back();
    }
    if (s == "-0") s = "0";
    return s;
}

// A slider position (0..1) to the value the control writes: clamped, snapped to the step.
inline std::string slider_value(const item& it, double frac) {
    frac = (std::min)(1.0, (std::max)(0.0, frac));
    double v = it.min + frac * (it.max - it.min);
    if (it.step > 0) v = it.min + std::round((v - it.min) / it.step) * it.step;
    v = (std::min)(it.max, (std::max)(it.min, v));
    return fmt_number(v, decimals_of(it.step));
}

inline double slider_frac(const item& it, const std::string& cur) {
    double v;
    if (!is_number(cur, &v) || it.max <= it.min) return 0;
    return (std::min)(1.0, (std::max)(0.0, (v - it.min) / (it.max - it.min)));
}

// One step of a slider (the arrow buttons / keyboard), clamped.
inline std::string slider_step(const item& it, const std::string& cur, int dir) {
    double v = it.min;
    is_number(cur, &v);
    v += dir * it.step;
    v = (std::min)(it.max, (std::max)(it.min, v));
    return fmt_number(v, decimals_of(it.step));
}

inline long index_of_value(const item& it, const std::string& cur) {
    for (size_t i = 0; i < it.values.size(); ++i) if (same_value(it.values[i], cur)) return static_cast<long>(i);
    return -1;
}

// The next / previous value of a toggle or a list, wrapping, as WaW's multiDef does.
inline std::string cycle(const item& it, const std::string& cur, int dir) {
    if (it.values.empty()) return cur;
    const long n = static_cast<long>(it.values.size());
    long i = index_of_value(it, cur);
    if (i < 0) i = dir > 0 ? -1 : 0;
    i = ((i + dir) % n + n) % n;
    return it.values[static_cast<size_t>(i)];
}

// What the row shows for a value.
inline std::string display_value(const item& it, const std::string& cur) {
    switch (it.k) {
    case kind::toggle: {
        const long i = index_of_value(it, cur);
        return i == 1 ? "on" : i == 0 ? "off" : cur;
    }
    case kind::select: {
        const long i = index_of_value(it, cur);
        if (i >= 0 && static_cast<size_t>(i) < it.labels.size()) return it.labels[static_cast<size_t>(i)];
        return cur.empty() ? "auto" : cur;
    }
    case kind::slider: {
        double v;
        if (!is_number(cur, &v)) return cur;
        return fmt_number(v, decimals_of(it.step));
    }
    default:
        return cur;
    }
}

// A value made safe for the console: one token inside quotes. The engine's own parser
// splits on ';' and newlines and ends a string at '"', so none of those survive.
inline std::string quote(std::string_view v) {
    std::string o = "\"";
    for (char c : v) {
        const unsigned char u = static_cast<unsigned char>(c);
        if (c == '"' || c == ';' || c == '\n' || c == '\r' || u < 0x20) continue;
        o.push_back(c);
    }
    o.push_back('"');
    return o;
}

// The console lines a change becomes. `seta`, so the dvar is archived: the engine then
// writes it to the profile's config.cfg on its next frame (write-through). Empty when the
// item may not be written at all.
inline std::vector<std::string> set_commands(const item& it, const std::string& value) {
    std::vector<std::string> out;
    if (it.k == kind::bind || it.k == kind::info || it.a == apply::site || it.dvar.empty()) return out;
    if (forbidden_dvar(it.dvar)) return out;
    out.push_back("seta " + it.dvar + " " + quote(value));
    for (const auto& [val, extra] : it.also)
        if (same_value(val, value))
            for (const auto& [d, x] : extra) if (!forbidden_dvar(d)) out.push_back("seta " + d + " " + quote(x));
    return out;
}

// ------------------------------------------------------------------ binds
// Key names as the engine writes them in a bind line (launcher/src/main/wawcfg.js KEY_RE).
inline std::string key_name_for_vk(unsigned vk) {
    if (vk >= '0' && vk <= '9') return std::string(1, static_cast<char>(vk));
    if (vk >= 'A' && vk <= 'Z') return std::string(1, static_cast<char>(vk));
    if (vk >= 0x70 && vk <= 0x7B) return "F" + std::to_string(vk - 0x70 + 1);   // VK_F1..F12
    if (vk >= 0x60 && vk <= 0x69) return "KP_" + std::to_string(vk - 0x60);     // numpad digits
    switch (vk) {
    case 0x20: return "SPACE";
    case 0x10: case 0xA0: case 0xA1: return "SHIFT";
    case 0x11: case 0xA2: case 0xA3: return "CTRL";
    case 0x12: case 0xA4: case 0xA5: return "ALT";
    case 0x09: return "TAB";
    case 0x0D: return "ENTER";
    case 0x08: return "BACKSPACE";
    case 0x26: return "UPARROW";
    case 0x28: return "DOWNARROW";
    case 0x25: return "LEFTARROW";
    case 0x27: return "RIGHTARROW";
    case 0x2D: return "INS";
    case 0x2E: return "DEL";
    case 0x24: return "HOME";
    case 0x23: return "END";
    case 0x21: return "PGUP";
    case 0x22: return "PGDN";
    case 0x13: return "PAUSE";
    case 0x14: return "CAPSLOCK";
    case 0xBA: return "SEMICOLON";
    case 0xBD: return "-";
    case 0xBB: return "=";
    case 0xDB: return "[";
    case 0xDD: return "]";
    case 0xDE: return "'";
    case 0xBC: return ",";
    case 0xBE: return ".";
    case 0xBF: return "/";
    case 0xDC: return "\\";
    default: return {};   // Esc, the console key, Windows keys: never bindable from here
    }
}

// `bind KEY "command"` lines of a config.cfg, in file order.
inline std::vector<std::pair<std::string, std::string>> parse_binds(std::string_view text) {
    std::vector<std::pair<std::string, std::string>> out;
    size_t i = 0;
    while (i < text.size()) {
        size_t j = text.find('\n', i);
        if (j == std::string_view::npos) j = text.size();
        std::string line(text.substr(i, j - i));
        i = j + 1;
        while (!line.empty() && (line.back() == '\r' || line.back() == ' ' || line.back() == '\t')) line.pop_back();
        size_t p = line.find_first_not_of(" \t");
        if (p == std::string::npos) continue;
        line = line.substr(p);
        if (line.size() < 6 || lower(line.substr(0, 5)) != "bind ") continue;
        std::string rest = line.substr(5);
        rest = rest.substr(rest.find_first_not_of(" \t") == std::string::npos ? rest.size() : rest.find_first_not_of(" \t"));
        const size_t sp = rest.find_first_of(" \t");
        if (sp == std::string::npos) continue;
        std::string key = rest.substr(0, sp);
        std::string cmd = rest.substr(sp + 1);
        cmd = cmd.substr(cmd.find_first_not_of(" \t") == std::string::npos ? cmd.size() : cmd.find_first_not_of(" \t"));
        if (cmd.size() >= 2 && cmd.front() == '"' && cmd.back() == '"') cmd = cmd.substr(1, cmd.size() - 2);
        for (auto& c : key) if (c >= 'a' && c <= 'z') c = static_cast<char>(c - 'a' + 'A');
        if (!key.empty() && !cmd.empty()) out.push_back({key, cmd});
    }
    return out;
}

// `seta name "value"` lines of a config.cfg (last one wins), lower-case names.
inline std::map<std::string, std::string> parse_setas(std::string_view text) {
    std::map<std::string, std::string> out;
    size_t i = 0;
    while (i < text.size()) {
        size_t j = text.find('\n', i);
        if (j == std::string_view::npos) j = text.size();
        std::string line(text.substr(i, j - i));
        i = j + 1;
        while (!line.empty() && (line.back() == '\r' || line.back() == ' ')) line.pop_back();
        const size_t p = line.find_first_not_of(" \t");
        if (p == std::string::npos) continue;
        line = line.substr(p);
        const size_t s1 = line.find(' ');
        if (s1 == std::string::npos) continue;
        const std::string verb = lower(line.substr(0, s1));
        if (verb != "seta" && verb != "set" && verb != "sets" && verb != "setu") continue;
        std::string rest = line.substr(s1 + 1);
        const size_t s2 = rest.find(' ');
        if (s2 == std::string::npos) continue;
        std::string name = lower(rest.substr(0, s2));
        std::string val = rest.substr(s2 + 1);
        if (val.size() >= 2 && val.front() == '"' && val.back() == '"') val = val.substr(1, val.size() - 2);
        out[name] = val;
    }
    return out;
}

// The keys bound to a command in a table of (key, command), in order.
inline std::vector<std::string> keys_of(const std::vector<std::pair<std::string, std::string>>& table, const std::string& command) {
    std::vector<std::string> out;
    for (const auto& [k, c] : table) if (lower(c) == lower(command)) out.push_back(k);
    return out;
}

// Bind `key` to `command` the way WaW's Controls menu does: with fewer than two keys the
// new one is added; with two, both are released and the new one is the only key. A key
// holds one command, so taking it frees it from whatever had it. Updates `table` and
// returns the console lines. An empty key clears the command (Backspace / Delete).
inline std::vector<std::string> bind_commands(std::vector<std::pair<std::string, std::string>>* table,
                                              const std::string& command, const std::string& key) {
    std::vector<std::string> out;
    std::vector<std::string> had = keys_of(*table, command);
    const bool clear_all = key.empty() || had.size() >= 2;
    auto drop_key = [&](const std::string& k) {
        table->erase(std::remove_if(table->begin(), table->end(), [&](const auto& e) { return e.first == k; }), table->end());
    };
    if (clear_all)
        for (const auto& k : had) {
            if (k == key) continue;
            out.push_back("unbind " + k);
            drop_key(k);
        }
    if (!key.empty()) {
        if (std::find(had.begin(), had.end(), key) == had.end() || clear_all) {
            drop_key(key);
            out.push_back("bind " + key + " " + quote(command));
            table->push_back({key, command});
        }
    }
    return out;
}

// The command a key holds in a table of (key, command), or "".
inline std::string command_of(const std::vector<std::pair<std::string, std::string>>& table, const std::string& key) {
    for (const auto& [k, c] : table) if (k == key) return c;
    return {};
}

// Free one key (the ENW console's `unbind <key>`): `unbind KEY`, whatever it held; the
// command's other key, if any, keeps it. Updates `table`. An empty key does nothing.
inline std::vector<std::string> unbind_commands(std::vector<std::pair<std::string, std::string>>* table, const std::string& key) {
    if (key.empty()) return {};
    table->erase(std::remove_if(table->begin(), table->end(), [&](const auto& e) { return e.first == key; }), table->end());
    return {"unbind " + key};
}

}  // namespace enw::settings
