#!/usr/bin/env python3
"""Generate an MSVC .def full of forwarders for a proxy DLL.

We load our DLL into the game by giving it the name of a DLL the game already
imports, and forwarding every export of the real one straight back to it (renamed
to <name>_org.dll). The Windows loader resolves forwarders itself, so the game
notices nothing.

Reads the export table straight out of the PE -- no dumpbin needed, so this runs
anywhere.

    python tools/dev/gen-proxy-def.py C:\\Users\\b\\ZombiesDev\\waw-base\\binkw32.dll \\
        --out shared/core/proxy/binkw32.def --forward-to binkw32_org
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path


def read_exports(path: Path) -> tuple[str, list[tuple[int, str]]]:
    """Return (dll name, [(ordinal, name), ...]) from a PE export directory."""
    d = path.read_bytes()

    if d[:2] != b"MZ":
        raise SystemExit(f"{path}: not a PE file")
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    if d[pe : pe + 4] != b"PE\0\0":
        raise SystemExit(f"{path}: bad PE signature")

    n_sections = struct.unpack_from("<H", d, pe + 6)[0]
    opt_size = struct.unpack_from("<H", d, pe + 20)[0]
    opt = pe + 24
    magic = struct.unpack_from("<H", d, opt)[0]
    if magic == 0x10B:      # PE32
        dir_off = opt + 96
    elif magic == 0x20B:    # PE32+
        dir_off = opt + 112
    else:
        raise SystemExit(f"{path}: unknown optional header magic {magic:#x}")

    exp_rva, exp_size = struct.unpack_from("<II", d, dir_off)
    if not exp_rva:
        raise SystemExit(f"{path}: no export directory")

    # Section table -> RVA to file offset.
    sections = []
    sec = pe + 24 + opt_size
    for i in range(n_sections):
        o = sec + i * 40
        vsize, vaddr, rawsize, rawptr = struct.unpack_from("<IIII", d, o + 8)
        sections.append((vaddr, max(vsize, rawsize), rawptr))

    def rva2off(rva: int) -> int:
        for vaddr, size, rawptr in sections:
            if vaddr <= rva < vaddr + size:
                return rawptr + (rva - vaddr)
        raise SystemExit(f"{path}: RVA {rva:#x} is outside every section")

    def cstr(rva: int) -> str:
        o = rva2off(rva)
        end = d.index(b"\0", o)
        return d[o:end].decode("ascii")

    e = rva2off(exp_rva)
    name_rva, ordinal_base, n_funcs, n_names = struct.unpack_from("<IIII", d, e + 12)
    addr_rva, names_rva, ords_rva = struct.unpack_from("<III", d, e + 28)

    dll_name = cstr(name_rva)
    functions = struct.unpack_from(f"<{n_funcs}I", d, rva2off(addr_rva))

    by_ordinal: dict[int, str] = {}
    if n_names:
        name_ptrs = struct.unpack_from(f"<{n_names}I", d, rva2off(names_rva))
        ordinals = struct.unpack_from(f"<{n_names}H", d, rva2off(ords_rva))
        for np, idx in zip(name_ptrs, ordinals):
            by_ordinal[ordinal_base + idx] = cstr(np)

    out = []
    for i, fn_rva in enumerate(functions):
        if fn_rva == 0:
            continue                       # a hole in the table
        ordinal = ordinal_base + i
        # A forwarder RVA points inside the export directory itself.
        forwarded = exp_rva <= fn_rva < exp_rva + exp_size
        name = by_ordinal.get(ordinal)
        if name is None:
            # Export by ordinal only -- we cannot write a named forwarder for it.
            print(f"  warning: ordinal {ordinal} has no name "
                  f"({'forwarder' if forwarded else 'code'}); skipped", file=sys.stderr)
            continue
        out.append((ordinal, name))

    out.sort()
    return dll_name, out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dll", type=Path, help="the ORIGINAL dll to mirror (read-only)")
    ap.add_argument("--out", type=Path, required=True, help="the .def to write")
    ap.add_argument("--forward-to", required=True,
                    help="module the forwarders point at, no .dll (e.g. binkw32_org)")
    args = ap.parse_args()

    dll_name, exports = read_exports(args.dll)
    target = args.forward_to

    lines = [
        f"; Generated by tools/dev/gen-proxy-def.py from {dll_name} -- DO NOT EDIT BY HAND.",
        f"; Source: {args.dll}",
        f"; {len(exports)} exports, every one forwarded to {target}.dll.",
        ";",
        "; Deploy: rename the game's original to " + target + ".dll, drop ours in as "
        + dll_name + ".",
        "",
        "EXPORTS",
    ]
    width = max((len(n) for _, n in exports), default= 0)
    for ordinal, name in exports:
        lines.append(f"    {name:<{width}} = {target}.{name} @{ordinal}")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="ascii")
    print(f"{args.out}: {len(exports)} forwarders -> {target}.dll")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
