// enw_t4.dll -- deployed into a dev game copy as binkw32.dll.
//
// HOW WE GET LOADED
//   CoDWaW.exe statically imports binkw32.dll (the Bink video codec). We take that
//   name, forward all 71 of its exports to binkw32_org.dll (shared/core/proxy/
//   binkw32.def, generated by tools/dev/gen-proxy-def.py) and the game loads us
//   for free. No injector, no CreateRemoteThread, nothing written to the Steam
//   install -- only to a copy under C:\Users\b\ZombiesDev.
//
// WHEN WE GET LOADED
//   Static imports are resolved BEFORE the PE entry point runs, and the entry
//   point is SteamStub's (.bind section). So at DllMain the game's .text is still
//   encrypted and every vault address points at noise. DllMain therefore does the
//   bare minimum and hands over to a thread, which waits for the stub.
#include "enw.hpp"

#include "component.hpp"
#include "frame.hpp"
#include "game.hpp"
#include "game_link.hpp"
#include "hook.hpp"
#include "logger.hpp"
#include "memory.hpp"
#include "scheduler.hpp"
#include "steamstub.hpp"

#include <cstdio>
#include <string>

namespace enw {
namespace {

HMODULE g_self = nullptr;
volatile LONG g_shutting_down = 0;

std::string module_path(HMODULE m) {
    char buf[MAX_PATH]{};
    ::GetModuleFileNameA(m, buf, MAX_PATH);
    return buf;
}

// `__DATE__`/`__TIME__` are the compile time of THIS translation unit, and on an
// incremental build an unchanged dllmain.cpp keeps the old ones. 2026-09-22 cost
// an hour to exactly that: three different DLLs all announced "build Sep 21 2026
// 16:18:51", so the banner could not tell which binary a player had run, and a
// stale-client bug was diagnosed as a component that failed to register. The
// file's own timestamp and size cannot go stale, so they go on the same line.
std::string file_stamp(const std::string& path) {
    WIN32_FILE_ATTRIBUTE_DATA a{};
    if (!::GetFileAttributesExA(path.c_str(), GetFileExInfoStandard, &a)) return "unreadable";
    SYSTEMTIME st{};
    FILETIME lt{};
    ::FileTimeToLocalFileTime(&a.ftLastWriteTime, &lt);
    ::FileTimeToSystemTime(&lt, &st);
    char buf[96]{};
    std::snprintf(buf, sizeof buf, "%04u-%02u-%02u %02u:%02u:%02u, %lu bytes", st.wYear,
                  st.wMonth, st.wDay, st.wHour, st.wMinute, st.wSecond,
                  static_cast<unsigned long>(a.nFileSizeLow));
    return buf;
}

void log_banner() {
    const std::string self = module_path(g_self);
    ENW_INFO("enw_t4 build %s %s (translation unit; the FILE is %s)", __DATE__, __TIME__,
             file_stamp(self).c_str());
    ENW_INFO("  dll : %s", self.c_str());
    ENW_INFO("  exe : %s", module_path(nullptr).c_str());
    ENW_INFO("  pid : %lu", static_cast<unsigned long>(::GetCurrentProcessId()));
    ENW_INFO("  cmd : %s", ::GetCommandLineA());
    ENW_INFO("  log : %s", log::file_path().c_str());
    ENW_INFO("  components registered: %u", static_cast<unsigned>(components::count()));
}

DWORD WINAPI loader_thread(LPVOID) {
    // Nothing here runs until the process loader lock is free, i.e. until after
    // the exe's own initialisation has begun. That is exactly what we want.
    log_banner();

    // Phase 1: the game's code is still encrypted. Components may start threads
    // and read config, but must not look at game memory.
    components::run_post_load();

    // The link is independent of the game's code: bring it up now so the host
    // agent sees the instance even if the game later fails to start.
    auto& link = game_link::get();
    if (link.configure_from_environment()) link.start();

    // Phase 2: wait for Steam's shim to decrypt .text.
    if (!steamstub::wait_for_decrypt()) {
        ENW_ERROR("enw_t4: game code never became readable. Components that touch game "
                  "memory will NOT run. The file log and the game link still work.");
        link.send_log("error", "steamstub never decrypted; game hooks disabled");
        return 0;
    }

    // Phase 3: check the vault's addresses against the real image before we trust them.
    const bool console_ok = game::verify();
    if (console_ok) log::enable_game_console(true);

    if (!hooks::init()) {
        ENW_ERROR("enw_t4: MinHook would not start; inline hooks are unavailable");
    }

    components::run_post_unpack();

    if (!hooks::enable_all()) {
        ENW_WARN("enw_t4: some hooks failed to enable (see above)");
    }

    ENW_INFO("enw_t4: hooks stage done (in-game console %s)", console_ok ? "ON" : "OFF");

    // Phase 4: the engine itself.
    //
    // SteamStub finishes ~100 ms into the process -- WAY before the engine has
    // started. Com_Printf is safe to call that early but the console does not
    // exist yet, so the text is thrown away (this cost us one test run). Anything
    // a human is meant to see has to wait for Com_Init to have run.
    if (!game::wait_for_engine()) {
        ENW_WARN("enw_t4: engine never reported ready; post_init components skipped");
        link.send_log("warn", "engine never reported ready");
        return 0;
    }

    // post_init runs ON THE GAME'S OWN THREAD.
    //
    // Com_Printf is callable from any thread (proven: 203 probe lines from the
    // loader thread reached the engine's console.log), but output produced in
    // the first moments after the engine comes up is only kept when it comes
    // from the main thread -- the identical off-thread line from that same
    // instant is dropped. Rather than make every component reason about that,
    // the whole phase is handed to the main thread.
    const HANDLE done = ::CreateEventA(nullptr, TRUE, FALSE, nullptr);
    scheduler::run_on_main([done]() {
        components::run_post_init();
        // The milestone line. If this appears in the game console, E1 is done.
        game::console_print("^2[ENW]^7 enw_t4 loaded - build %s %s, pid %lu\n", __DATE__, __TIME__,
                            static_cast<unsigned long>(::GetCurrentProcessId()));
        if (done) ::SetEvent(done);
    });

    bool on_main = false;
    if (done && ::WaitForSingleObject(done, 20000) == WAIT_OBJECT_0) {
        on_main = true;
    } else {
        // The pump is driven by a Dvar_FindVar detour, and the engine stops
        // calling it once it settles. Better late and off-thread than never.
        ENW_WARN("enw_t4: the main-thread pump never ran our post_init job within 20 s; "
                 "running it on the loader thread instead (output may be dropped). "
                 "This is the stopgap pump - it needs a real frame hook.");
        components::run_post_init();
    }
    if (done) ::CloseHandle(done);

    // ENW_PRINT_PROBE=1: find out which Com_Printf channel the engine actually
    // shows, and from which moment in startup. See docs/kickstart/foundation.md.
    {
        char probe[8]{};
        if (::GetEnvironmentVariableA("ENW_PRINT_PROBE", probe, sizeof(probe)) && probe[0] == '1') {
            game::run_print_probe();
        }
    }

    ENW_INFO("enw_t4: ready (post_init ran on %s)", on_main ? "the game thread" : "the loader thread");

    // ...and once more, later, on purpose.
    //
    // The engine spends the first seconds of startup adding and hiding console
    // channels as it execs default.cfg / language.cfg / the profile config, and a
    // burst of Com_Printf lines emitted during that churn is only partly kept:
    // measured across five runs, anywhere from 1 to 7 of the same 7 banner lines
    // reached console.log. Nothing is wrong with the printing -- the filter state
    // is just moving underneath us. So we re-announce once, after it settles, to
    // give a deterministic "we are here" line.
    ::Sleep(3000);
    scheduler::run_on_main([]() {
        game::console_print("^2[ENW]^7 enw_t4 ready - build %s %s, pid %lu\n", __DATE__, __TIME__,
                            static_cast<unsigned long>(::GetCurrentProcessId()));
    });
    // The pump may already have stopped (see components/main_thread.cpp), so do
    // not rely on the queue alone.
    ::Sleep(500);
    if (!game::console_available()) return 0;
    game::console_print("^2[ENW]^7 enw_t4 ready - build %s %s, pid %lu\n", __DATE__, __TIME__,
                        static_cast<unsigned long>(::GetCurrentProcessId()));

    // Is the per-frame tick actually running? This is the one number that says
    // whether WinMain reached its loop, so print it where everyone can see it.
    ::Sleep(2000);
    const uint64_t frames = frame::count();
    const auto st = scheduler::snapshot();
    game::console_print("^7[ENW] frames=%llu subs=%u  main-thread jobs ran=%llu dropped=%llu\n",
                        static_cast<unsigned long long>(frames),
                        static_cast<unsigned>(frame::subscriber_count()),
                        static_cast<unsigned long long>(st.ran),
                        static_cast<unsigned long long>(st.dropped));
    if (frames > 0) {
        ENW_INFO("enw_t4: PER-FRAME TICK IS LIVE (%llu frames). Steady-state "
                 "scheduler::run_on_main() and game-link commands now work.",
                 static_cast<unsigned long long>(frames));
    } else {
        ENW_WARN("enw_t4: still zero frames - WinMain has not reached its loop (0x5FF4E0).");
    }
    link.send_log("info", "enw_t4 ready");
    return 0;
}

}  // namespace
}  // namespace enw

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID) {
    switch (reason) {
        case DLL_PROCESS_ATTACH: {
            enw::g_self = module;
            // DllMain for a static import runs on the process's initial thread,
            // i.e. the game's main thread. Free, and the only reliable place to
            // learn its id.
            enw::scheduler::set_main_thread(::GetCurrentThreadId());
            // We never care about thread attach/detach, and skipping them keeps us
            // out of the game's very hot thread churn.
            ::DisableThreadLibraryCalls(module);
            enw::log::init();

            // Everything real happens off the loader lock.
            const HANDLE t = ::CreateThread(nullptr, 0, enw::loader_thread, nullptr, 0, nullptr);
            if (t) {
                ::CloseHandle(t);
            } else {
                ENW_ERROR("enw_t4: CreateThread failed (%lu) - the DLL is loaded but inert",
                          ::GetLastError());
            }
            break;
        }
        case DLL_PROCESS_DETACH: {
            if (::InterlockedExchange(&enw::g_shutting_down, 1) != 0) break;
            // If the loader thread is still waiting on SteamStub, let it go now
            // rather than have it poll into a torn-down process.
            enw::steamstub::abort_wait();
            enw::game::abort_wait();
            enw::components::run_pre_destroy();
            enw::game_link::get().stop();
            enw::hooks::shutdown();
            enw::log::shutdown();
            break;
        }
        default:
            break;
    }
    return TRUE;
}
